FORMAT: 1A
HOST: http://api.lunarandflo.com

# Lunar & Flo

Lunar & Flo API enabling interaction with the L&F server.

## Heartbeat [/heartbeat]

Check the API's pulse.

### Check Heartbeat [GET]

+ Response 200 (application/json)

        {
            "hearbeat": "beep boop"
        }


## Authentication [/auth]

### Authenticate User [POST]

Post to this action to login. 
It accepts a user's email and password, and returns a JWT which must be attached in the Authorization header of every subsequent request (except `heartbeat`).

+ Request (application/json)

        {
            "email": "test@example.com",
            "password": "password"
        }

+ Response 200 (application/json)

        {
            "auth_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjZkMDU2ZjMtMTkwZS00ZTQ2LTllNjMtMWI3MTYxMjJlMjg4In0.G-LSkJg8AhpdXEEAakjcQNdFxXse4et8uwdFNvZwU4o",
            "user": {
                "id": "26d056f3-190e-4e46-9e63-1b716122e288",
                "email": "test@example.com"
            }
        }

+ Response 401 (application/json)

        {
            "errors": [
                "Invalid Username/Password"
            ]
        }

## Users [/users/{user_id}]


+ Parameters

    + user_id: `26d056f3-190e-4e46-9e63-1b716122e288` (string) - The ID of the user (or `me`)
    
+ Attributes(User)

### Me [GET]

Get the current user.

+ Response 200 (application/json)

    + Attributes (User)
    
### Update [PUT]

Update the current user

+ Request (application/json)

    + Attributes (User)

+ Response 200 (application/json)

    + Attributes (User)
        
## Check Ins [/users/{user_id}/check_ins]

+ Parameters

    + user_id: `26d056f3-190e-4e46-9e63-1b716122e288` (string) - The ID of the user (or `me`)

+ Attributes (Check In)

### All user check ins [GET]

List all user check ins.

+ Response 200 (application/json)

    + Attributes (array[Check In])
    
### Create check in [POST]

Create a check in for a user

+ Request
    
    + Attributes
        
        + symptom_ids (array[string], required) - An array of Symptom IDs the user has selected
        + lat: `51.507351` (number) - Latitude at time of check in
        + lng: `-0.127758` (number) - Longitude at time of check in

+ Response 201 (application/json)

    + Attributes (Check In)
        
### View check in [GET /users/{user_id}/check_ins/{check_in_id}]

Get a single check in

+ Parameters

    + user_id: `26d056f3-190e-4e46-9e63-1b716122e288` (string, required) - The ID of the user (or `me`)

    + check_in_id: `26d056f3-190e-4e46-9e63-1b716122e288` (string, required) - The ID of the check in

+ Response 200 (application/json)

    + Attributes (Check In)

## History [/users/{user_id}/history{?before}]

+ Parameters

    + user_id: `26d056f3-190e-4e46-9e63-1b716122e288` (string, required) - The ID of the user (or `me`)
    
    + before: `2016-01-01` (string, optional) - The latest date to include


### View check in history [GET]

View a month of a user's check in history

+ Response 200 (application/json)

        {
            "2016-09-14":null,
            "2016-09-13":{
                "id":"18d9895f-95c2-4441-b574-85cb7953e012",
                "lat":1.01,
                "lng":-51.4,
                "symptoms": [],
                "weather_report":null
            },
            "2016-09-12":null,
            "2016-09-11":null,
            "2016-09-10":null,
            "2016-09-09":null,
            "2016-09-08":null,
            "2016-09-07":null,
            "2016-09-06":null,
            "2016-09-05":null,
            "2016-09-04":null,
            "2016-09-03":null,
            "2016-09-02":null,
            "2016-09-01":null,
            "2016-08-31":null,
            "2016-08-30":null,
            "2016-08-29":null,
            "2016-08-28":null,
            "2016-08-27":null,
            "2016-08-26":null,
            "2016-08-25":null,
            "2016-08-24":null,
            "2016-08-23":null,
            "2016-08-22":null,
            "2016-08-21":null,
            "2016-08-20":null,
            "2016-08-19":null,
            "2016-08-18":null,
            "2016-08-17":null,
            "2016-08-16":null,
            "2016-08-15":null
        }

## Data Structures

### User

+ id: `26d056f3-190e-4e46-9e63-1b716122e288` (string, required)
+ email: `test@example.com` (string, required)
+ name: `Joe Bloggs` (string)

### Check In

+ id: `26d056f3-190e-4e46-9e63-1b716122e288` (string, required)
+ lat: `51.507351` (number) - Latitude at time of check in
+ lng: `-0.127758` (number) - Longitude at time of check in
+ symptoms (array[Symptom]) - Array of selected symptoms
+ weather_report (Weather Report) - Attached weather and moon data

### Symptom

+ id: `26d056f3-190e-4e46-9e63-1b716122e288` (string, required)

### Weather Report

+ id: `26d056f3-190e-4e46-9e63-1b716122e288` (string, required)
